- .gitignore
- .npmrc
- README.md
- crypt-key-accessor.js
- in-crypt.js
- logger.js
- package-lock.json
- package.json
- storage.js
- tests/unit/crypt-key-accessor-tests.js
- tests/unit/in-crypt-tests.js
- tests/unit/logger-tests.js
This is a port of old repo.
The main changes:
- improved logger tests
- add ability to specify custom logger
> EN-939 Custom logger support

- .gitignore
- .travis.yml
- package.json
- sonar-project.properties
Link to Jira Task/User Story/Bug/Epic:
SEC-15
Code Quality
------------
[+] Ensure code compiles or passes linter locally.
[+] Ensure all unit tests pass.
[-] Do your best to ensure integration tests pass. This is not always possible and should not gate the merge.
[-] Remove, ignore, or mark pending any brittle tests.
> SEC-15 Initial integration with TravisCI + SonarCloud

- pull_request_template.md
Link to Jira Task/User Story/Bug/Epic:
[] ARC-19
Code Quality
------------
[x] Ensure code compiles or passes linter locally.
[x] Ensure all unit tests pass.
[x] Do your best to ensure integration tests pass. This is not always possible and should not gate the merge.
[x] Remove, ignore, or mark pending any brittle tests.
> [ARC-19] Update PR Checklist

- pull_request_template.md
[x]
------------
[x] Ensure code compiles and passes Sonar Lint.
[x] Do your best to ensure integration tests pass. If they don't then...
[x] Remove, ignore, or mark pending any brittle tests.
[x] Remove commented out code.
Target Release
--------------
[x] Please put the target release vehicle this needs to be bundled with.
[x] Did you increment the version in package.json? What is the new version?
No version Change
> [ARC-19] Update to have check boxes work correctly

- .travis.yml
- [SEC-49] Add Snyk scan into CI.
------------
No code changes. CI pipeline change only.
[SEC-49]: https://incountry.atlassian.net/browse/SEC-49
> SEC-49 Add Snyk scan to CI pipeline.

- countries-cache.js
- package-lock.json
- package.json
- storage.js
- tests/integration/storage-tests.js
------------
Target Release
--------------
> [FB_EN-1293]

- package-lock.json
- package.json
- storage.js
- tests/unit/storage-tests.js
- [https://incountry.atlassian.net/browse/EN-1170]
------------
Target Release
--------------
- [-] Please put the target release vehicle this needs to be bundled with.
- [-] Did you increment the version in package.json? What is the new version?
> Fb en 1170

- storage.js
- tests/unit/storage-tests.js
- [https://incountry.atlassian.net/browse/EN-1360]
------------
Target Release
--------------
> Fb en 1360

- package-lock.json
- package.json
- storage.js
- tests/unit/storage-tests.js
- [https://incountry.atlassian.net/browse/EN-1389 ]
------------
Target Release
--------------
> Add override support for update operation.

- in-crypt.js
- package-lock.json
- tests/unit/in-crypt-tests.js
https://incountry.atlassian.net/browse/EN-1417
https://incountry.atlassian.net/browse/EN-1417
------------
Target Release
--------------
> FB_EN-1417 Change from using Hex for encrypted Payloads to Base64 in NodeJS SDK

- README.md
[FIX] fix README.md typos
- https://incountry.atlassian.net/browse/EN-1529
------------
Target Release
--------------
> EN-1529 Fix NodeJS Readme typos 

- in-crypt.js
- package-lock.json
- package.json
- secret-key-accessor.js
- storage.js
- tests/unit/crypt-key-accessor-tests.js
- tests/unit/in-crypt-tests.js
- tests/unit/storage-tests.js
- utils.js
- Add ability to pass multiple keys with KeysObject
- Add KeysObject validation via io-ts lib (https://github.com/gcanti/io-ts)
- Add some jsdocs
------------
Target Release
--------------
> EN-1584 SecretKeyAccessor - Multiple keys object

- storage.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-1587 Node.js SDK should have batchWrite method

- examples/migration.js
------------
Target Release
--------------
> EN-1593 migration script example

- storage.js
- [EN-1731 ](https://incountry.atlassian.net/browse/EN-1731)
------------
Target Release
--------------
> EN-1731 Fix findOne doesn't work bug

- README.md
- secret-key-accessor.js
[ENH] update README.md with information about SecretKeyAccessor enhancement, batchWrite, migrate and migration script example
- https://incountry.atlassian.net/browse/EN-1671
------------
Target Release
--------------
> EN-1671 Add migration/key rotation README notes for Node.js SDK

- README.md
- foreach-async.js
- storage.js
- tests/integration/storage-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-1780 remove batchAsync

- package.json
- tests/unit/countries-cache-tests.js
- tests/unit/crypt-key-accessor-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-1743 Node.js SDK unit tests code coverage improvement

- in-crypt.js
- storage.js
- tests/unit/in-crypt-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-1776 Add plaintext (in no-encryption mode) crypto-version support to Node.js SDK

- in-crypt.js
- secret-key-accessor.js
- storage.js
- tests/integration/find-one-record-tests.js
- tests/integration/find-records-tests.js
- tests/integration/read-tests.js
- tests/integration/update-record-tests.js
- tests/unit/in-crypt-tests.js
- tests/unit/storage-tests.js
- https://incountry.atlassian.net/browse/EN-1826
------------
Target Release
--------------
> EN-1826 Merge RC_1.0.0 into develop for Node.js SDK

- errors.js
- storage.js
- tests/integration/delete-tests.js
- tests/integration/find-one-record-tests.js
- tests/integration/find-records-tests.js
- tests/integration/read-tests.js
- tests/integration/storage-tests.js
- tests/integration/update-record-tests.js
- tests/integration/write-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-1564 refactor storage methods return format and errors

- package.json
[ENH] bump version to 1.0.0
- https://incountry.atlassian.net/browse/EN-1874
------------
Target Release
--------------
> EN-1874 https://incountry.atlassian.net/browse/EN-1874

- .eslintrc
- .travis.yml
- README.md
- countries-cache.js
- crypt-key-accessor.js
- foreach-async.js
- in-crypt.js
- logger.js
- package-lock.json
- package.json
- secret-key-accessor.js
- storage.js
- tests/integration/countries-cache-tests.js
- tests/integration/storage-tests.js
- tests/unit/crypt-key-accessor-tests.js
- tests/unit/in-crypt-tests.js
- tests/unit/logger-tests.js
- tests/unit/storage-tests.js
- https://incountry.atlassian.net/browse/EN-1874
------------
Target Release
--------------
> EN-1874 RC 1.0.0

- README.md
- https://incountry.atlassian.net/browse/EN-1901
------------
Target Release
--------------
> EN-1901 Node.js SDK fix readme version note

- README.md
[FIX] update README.md formatting
- https://incountry.atlassian.net/browse/EN-1903
------------
Target Release
--------------
> EN-1903 Node.js SDK fix readme 

- README.md
- https://incountry.atlassian.net/browse/EN-1874
------------
Target Release
--------------
> EN-1874 Node.js Release RC_1.0.0 - 3

- README.md
[ENH] remove important note from README
- https://incountry.atlassian.net/browse/EN-1906
------------
Target Release
--------------
> EN-1906 [Node.js SDK] Remove important notice from README

- errors.js
- secret-key-accessor.js
- tests/unit/crypt-key-accessor-tests.js
- utils.js
------------
Target Release
--------------
> EN-1905 validation error messages

- README.md
- https://incountry.atlassian.net/browse/EN-1942
------------
Target Release
--------------
> EN-1942 [Node.js SDK] Release v1.0.0a

- README.md
- package.json
- https://incountry.atlassian.net/browse/EN-1942
------------
Target Release
--------------
> EN-1942 [Node.js SDK] Release v1.0.0a - 2

- storage.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-1931 batchWrite format

- countries-cache.js
- tests/unit/countries-cache-tests.js
------------
Target Release
--------------
> EN-1788 countries cache call singnature - default without timestamp

- in-crypt.js
- tests/unit/in-crypt-tests.js
------------
Target Release
--------------
> EN-1875 Remove decryptV0

- pull_request_template.md
- storage.js
- tests/unit/storage-tests.js
- [EN-1566](https://incountry.atlassian.net/browse/EN-1566)
------------
Target Release
--------------
> EN-1566: Add Node.js SDK language and version as header to all requests

- in-crypt.js
- storage.js
- tests/integration/delete-tests.js
- tests/integration/find-one-record-tests.js
- tests/integration/find-records-tests.js
- tests/integration/read-tests.js
- tests/integration/update-record-tests.js
- tests/integration/write-tests.js
- tests/unit/in-crypt-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-1789 Storage constructor arguments checking

- package.json
- tests/test-helpers/popapi-nock.js
- tests/unit/errors-test.js
- tests/unit/in-crypt-tests.js
- tests/unit/logger-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-1839 [Node.js SDK] Improve Storage unit tests

- storage.js
- tests/unit/storage-tests.js
- https://incountry.atlassian.net/browse/EN-2033
------------
Target Release
--------------
> EN-2033 [Node.js SDK] Do not throw error if can't parse/decrypt record in Find results

- errors.js
- package.json
- storage.js
- tests/unit/storage-tests.js
- utils.js
- https://incountry.atlassian.net/browse/EN-1838
------------
Target Release
--------------
> EN-1838 [Node.js SDK] Enhanced custom logger

- README.md
- in-crypt.js
- package-lock.json
- tests/unit/in-crypt-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-2064 [Node.js SDK] remove decryptStub. Throw exception instead (thus the record would fall to errors in Storage.find)

- README.md
- dto/record.js
- errors.js
- secret-key-accessor.js
- storage.js
- tests/integration/delete-tests.js
- tests/integration/find-one-record-tests.js
- tests/integration/find-records-tests.js
- tests/integration/read-tests.js
- tests/integration/update-record-tests.js
- tests/integration/write-tests.js
- tests/unit/storage-tests.js
- utils.js
- validation/country-code.js
- validation/find-options.js
- validation/limit.js
- validation/record-key.js
- validation/record.js
- validation/records.js
- validation/secrets-data.js
- validation/utils.js
- make country code first argument for all calls
- remove country code from record object
- simplify call signature for `delete` and `read` - the second argument is `key` string and not an object 
- remove `_` and `Async` from method's names
------------
Target Release
--------------
> EN-1975 Validate public method arguments

- README.md
- errors.js
- in-crypt.js
- package-lock.json
- package.json
- storage.js
- tests/unit/in-crypt-tests.js
- tests/unit/storage-tests.js
- utils.js
- https://incountry.atlassian.net/browse/EN-2119
------------
Target Release
--------------
> EN-2119 [Node.js SDK] Release RC_1.1.0

- package-lock.json
- package.json
[ENH] bumped version in package.json/package-lock.json
- https://incountry.atlassian.net/browse/EN-2116
------------
Target Release
--------------
> EN-2116 [Node.js SDK] bump RC_1.1.0 version

- .eslintrc
- .travis.yml
- README.md
- api-client.js
- in-crypt.js
- logger.js
- package-lock.json
- package.json
- storage.js
- tests/unit/crypt-key-accessor-tests.js
- tests/unit/in-crypt-tests.js
- tests/unit/logger-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> EN-2082 [Node.js SDK] Merge master into dev branch (after 1.1.0 release)

- storage.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> [EN-1883] [Node.js SDK] To lowercase on all keys

- storage.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> [EN-1789][Node.js SDK] Storage class has no validation for constructor parameters - 2

- errors.js
- storage.js
- tests/unit/error-reporter-test.js
- tests/unit/storage-tests.js
- validation/api-responses/find-response.js
- validation/api-responses/record-response.js
- validation/api-responses/write-response.js
- validation/error-reporter.js
- validation/find-options.js
- validation/limit.js
- validation/record.js
- validation/records.js
- validation/secrets-data.js
- validation/utils.js
-  make error messages more human-friendly
------------
Target Release
--------------
> [EN-1975] [Node.js SDK] Validate public method arguments - 2

- api-client.js
- tests/unit/api-client-test.js
------------
Target Release
--------------
> EN-2122 [Node.js SDK] Throw an error if failed to retrieve countries from portal-backend

- README.md
- errors.js
- examples/migration.js
- in-crypt.js
- secret-key-accessor.js
- storage.js
- tests/integration/common.js
- tests/integration/delete-tests.js
- tests/integration/find-one-record-tests.js
- tests/integration/find-records-tests.js
- tests/integration/read-tests.js
- tests/integration/update-record-tests.js
- tests/integration/write-tests.js
- tests/unit/crypt-key-accessor-tests.js
- tests/unit/in-crypt-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> [EN-2207] [Node.js SDK] Validate secrets data right after SecretKeyAccessor creation

- .travis.yml
- tests/integration/batchWrite-tests.js
- tests/integration/common.js
- tests/integration/find-one-record-tests.js
- tests/integration/find-records-tests.js
- tests/integration/normalize-key-tests.js
- tests/integration/normolize-key-tests.js
- tests/integration/update-record-tests.js
------------
Target Release
--------------
> [EN-1883] [Node.js SDK] To lowercase on all keys tests

- in-crypt.js
- tests/integration/custom-enc-test.js
- tests/integration/find-one-record-tests.js
- tests/integration/find-records-tests.js
fix custom decrypt; 
add basic integration test
------------
Target Release
--------------
> [EN-1763] [Node.js SDK] Add custom encryption support - 2

- storage.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> [EN-2321] findOne should use limit:1

- README.md
- errors.js
- storage.js
- tests/integration/batchWrite-tests.js
- tests/integration/read-tests.js
- tests/integration/write-tests.js
- tests/unit/storage-tests.js
- utils.js
- validation/find-options.js
- validation/record.js
- validation/secrets-data.js
- validation/utils.js
------------
Target Release
--------------
> SDK-2 [Node.js SDK]  README updates with minor validation tweaks

- package-lock.json
- package.json
- [SDK-62](https://incountry.atlassian.net/browse/SDK-62)
------------
Target Release
--------------
> SDK-62 [Node.js SDK] Review security alerts

- README.md
------------
Target Release
--------------
> [SDK-71][Node.js SDK] reorganize files and folders - 2

- README.md
- lib/in-crypt.js
- lib/validation/custom-encryption-configs.js
- tests/unit/in-crypt-tests.js
------------
Target Release
--------------
> [SDK-74][Node.js SDK] Storage doesn't init with custom encryption

- README.md
- lib/in-crypt.js
- lib/validation/custom-encryption-configs.js
- tests/unit/in-crypt-tests.js
------------
Target Release
--------------
> [SDK-74][Node.js SDK] Storage doesn't init with custom encryption - 2 RC

- README.md
- countries.md
- pull_request_template.md
- [SDK-78](https://incountry.atlassian.net/browse/SDK-78)
------------
Target Release
--------------
> SDK-78 [Node.js SDK] Move countries README.md updates to v1.1.1

- package.json
- [SDK-94](https://incountry.atlassian.net/browse/SDK-94)
------------
Target Release
--------------
> SDK-94 [Node.js SDK] Bump version for RC_1.1.1

- README.md
- countries.md
- package.json
- pull_request_template.md
- [SDK-91](https://incountry.atlassian.net/browse/SDK-91)
------------
Target Release
--------------
> SDK-91 [Node.js SDK] Release RC_1.1.1

- README.md
- [SDK-99](https://incountry.atlassian.net/browse/SDK-99)
------------
Target Release
--------------
> [SDK-99][Node.js SDK] postpone $not filter for find untill v2.1.0

- lib/storage.js
- lib/validation/exact.js
- lib/validation/excess.js
- lib/validation/find-filter.js
- tests/integration/find-records-tests.js
- tests/unit/storage-tests.js
- [SDK-88](https://incountry.atlassian.net/browse/SDK-88)
------------
Target Release
--------------
> [SDK-88][Node.js SDK] Find with filter $not doesn't work for keys fields

- README.md
- examples/migration.js
- lib/api-client.js
- lib/secret-key-accessor.js
- lib/storage.js
- lib/validation/storage-options.js
- tests/unit/storage-tests.js
- [SDK-100](https://incountry.atlassian.net/browse/SDK-100)
------------
Target Release
--------------
> [SDK-100][Node.js SDK] Fix mandatory endpoint param

- README.md
- examples/migration.js
- lib/api-client.js
- lib/secret-key-accessor.js
- lib/storage.js
- lib/validation/storage-options.js
- tests/unit/storage-tests.js
- [SDK-104](https://incountry.atlassian.net/browse/SDK-104)
------------
Target Release
--------------
> [SDK-104][Node.js SDK] Merge "RC_2.0.0" branch into "develop" branch 

- lib/api-client.js
- lib/auth-client.js
- lib/storage.js
- lib/validation/storage-options.js
- tests/test-helpers/auth-nock.js
- tests/unit/api-client-test.js
- tests/unit/auth-client-test.js
- tests/unit/storage-tests.js
- [SDK-32](https://incountry.atlassian.net/browse/SDK-32)
------------
Target Release
--------------
> SDK-32 [Node.js SDK] use oAuth protocol for PoPAPI communication

- README.md
- lib/api-client.js
- lib/in-crypt.js
- lib/index.js
- lib/secret-key-accessor.js
- lib/storage.js
- lib/utils.js
- lib/validation/custom-encryption-configs-deep.js
- lib/validation/custom-encryption-configs.js
- tests/integration/common.js
- tests/unit/crypt-key-accessor-tests.js
- tests/unit/in-crypt-tests.js
- tests/unit/storage-tests.js
------------
Target Release
--------------
> [SDK-75][Node.js SDK] Decouple validations from constructor

- lib/validation/api-responses/record-response.js
- package.json
- tests/unit/validation/api-response/record-response-test.js
- [SDK-110](https://incountry.atlassian.net/browse/SDK-110)
------------
Target Release
--------------
> [SDK-110][Node.js SDK] Make http response version validation less strict

- lib/storage.js
- tests/unit/storage-tests.js
- [SDK-113](https://incountry.atlassian.net/browse/SDK-113)
------------
Target Release
--------------
> SDK-113 [Node.js SDK] Fix key hashing

- tests/unit/storage-tests.js
- [SDK-117](https://incountry.atlassian.net/browse/SDK-117)
------------
Target Release
--------------
> SDK-117 [Node.js SDK] Add universal unit tests for encrypt/decrypt payload methods

- src/api-client.ts
- src/errors.ts
- src/normalize-errors-decorator.ts
- src/storage.ts
- src/validation/validate-decorator.ts
- tests/unit/storage-tests.js
- [SDK-121](https://incountry.atlassian.net/browse/SDK-121)
------------
Target Release
--------------
> SDK-121 [Node.js SDK] Improve error messages 

- README.md
- [SDK-132](https://incountry.atlassian.net/browse/SDK-132)
------------
Target Release
--------------
> SDK-132 [Node.js SDK] Add oAuth section to README.md

- .travis.yml
- [SDK-134](https://incountry.atlassian.net/browse/SDK-134)
------------
Target Release
--------------
> SDK-134 [Node.js SDK] Fix SonarCloud test coverage integration

- .travis.yml
- [SDK-134](https://incountry.atlassian.net/browse/SDK-134)
------------
Target Release
--------------
> SDK-134 [Node.js SDK] Fix SonarCloud test coverage integration - 2

- README.md
- src/api-client.ts
- src/auth-client.ts
- src/storage.ts
- src/validation/storage-options.ts
- tests/unit/api-client-test.js
- tests/unit/auth-client-test.js
- [SDK-137](https://incountry.atlassian.net/browse/SDK-137)
------------
Target Release
--------------
> SDK-137 [Node.js SDK] add ability to provide endpoint mask (and update minipop token acquisition)

- package.json
- [SDK-155](https://incountry.atlassian.net/browse/SDK-155)
------------
Target Release
--------------
> SDK-155 [Node.js SDK] Release RC_2.0.0 - resolve conflicts with master

- src/api-client.ts
- src/auth-client.ts
- src/countries-cache.ts
- src/storage.ts
- tests/test-helpers/auth-nock.ts
- tests/unit/api-client-test.ts
- tests/unit/auth-client-test.ts
- tests/unit/countries-cache-tests.ts
- [SDK-153](https://incountry.atlassian.net/browse/SDK-153)
------------
Target Release
--------------
> SDK-153 [Node.js SDK] add default regional auth servers 

- src/secret-key-accessor.ts
- src/validation/utils.ts
- [SDK-164](https://incountry.atlassian.net/browse/SDK-164)
------------
Target Release
--------------
> SDK-164 [Node.js SDK] Cannot install package from develop branch

- README.md
- src/auth-client.ts
- src/storage.ts
- src/validation/storage-options.ts
- tests/unit/auth-client-test.ts
- tests/unit/storage-tests.ts
- tests/unit/validation/storage-options-test.ts
- [SDK-174](https://incountry.atlassian.net/browse/SDK-174)
------------
Target Release
--------------
> SDK-174 [Node.js SDK] add auth_endpoints Storage option

- README.md
- package.json
- tests/unit/storage-tests.ts
- [SDK-171](https://incountry.atlassian.net/browse/SDK-171)
------------
Target Release
--------------
> SDK-171 [Node.js SDK] Release RC_2.1.0 - readme update, merge with master

- package.json
- [SDK-171](https://incountry.atlassian.net/browse/SDK-171)
------------
Target Release
--------------
> SDK-171 [Node.js SDK] Release RC_2.1.0 - bump version

- .travis.yml
- README.md
- src/storage.ts
- [SDK-181](https://incountry.atlassian.net/browse/SDK-181)
------------
Target Release
--------------
> SDK-181 [Node.js SDK] Add badges to README

- .travis.yml
- [SDK-212](https://incountry.atlassian.net/browse/SDK-212)
------------
Target Release
--------------
> SDK-212 [Node.js SDK] Change GIT clone configuration for Travis

- .travis.yml
- [SDK-212](https://incountry.atlassian.net/browse/SDK-212)
------------
Target Release
--------------
> SDK-212 [Node.js SDK] Change GIT clone configuration for Travis, remove duplicating script

- README.md
- examples/migration.js
- sonar-project.properties
- src/api-client.ts
- tests/unit/storage-tests.ts
- [SDK-208](https://incountry.atlassian.net/browse/SDK-208)
------------
Target Release
--------------
> [SDK-208][Node.js SDK] [EOS-54] Update README to mention Schema 2.2 changes

- README.md
- [SDK-208](https://incountry.atlassian.net/browse/SDK-208)
------------
Target Release
--------------
> SDK-208 [Node.js SDK] Update README to mention Schema 2.2 changes - 2

- package.json
- tests/unit/storage-tests.ts
- [SDK-213](https://incountry.atlassian.net/browse/SDK-213)
------------
Target Release
--------------
> SDK-213 [Node.js SDK] Release RC_3.0.0 - resolve master conflicts

- src/storage.ts
- src/validation/utils.ts
- tests/unit/storage-tests.ts
- tests/unit/validation/find-filter-test.ts
- tests/unit/validation/utils-test.ts
- [SDK-217](https://incountry.atlassian.net/browse/SDK-217)
------------
Target Release
--------------
> SDK-217 [Node.js SDK] Fix unit tests coverage

- README.md
- [SDK-213](https://incountry.atlassian.net/browse/SDK-213)
------------
Target Release
--------------
> SDK-213 [Node.js SDK] Release v3.0.0 - README updates

- tests/integration/find-one-record-tests.ts
- tests/integration/find-records-tests.ts
- [SDK-213](https://incountry.atlassian.net/browse/SDK-213)
------------
Target Release
--------------
> SDK-213 [Node.js SDK] Release v3.0.0 - disable faulty int test

- README.md
- [SDK-213](https://incountry.atlassian.net/browse/SDK-213)
------------
Target Release
--------------
> SDK-213 [Node.js SDK] Release v3.0.0 - remove build badge

- README.md
Reverts incountry/sdk-nodejs#142
> Revert "SDK-213 [Node.js SDK] Release v3.0.0 - remove build badge"

- src/api-client.ts
- tests/unit/storage-tests.ts
- [SDK-220](https://incountry.atlassian.net/browse/SDK-220)
------------
Target Release
--------------
> [Node.js SDK] Pass POPAPI response headers to logger

- src/storage.ts
- tests/unit/storage-tests.ts
- [SDK-221](https://incountry.atlassian.net/browse/SDK-221)
------------
Target Release
--------------
> SDK-221 [NodeJS SDK] Fix bug at 'Migration' method

- package.json
- sonar-project.properties
- [SDK-223](https://incountry.atlassian.net/browse/SDK-223)
------------
Target Release
--------------
> SDK-223 [Node.js SDK] Release SDK v3.0.1

- src/normalize-errors-decorator.ts
- tests/unit/normalize-errors-decorator-test.ts
- [SDK-226](https://incountry.atlassian.net/browse/SDK-226)
------------
Target Release
--------------
> SDK-226 [Node.js SDK] Fix error stack trace

- README.md
- [SDK-233](https://incountry.atlassian.net/browse/SDK-233)
------------
Target Release
--------------
> [SDK-233] Add non hashing mode for key1-key10 - 2 README 

- package-lock.json
- package.json
- [SDK-240](https://incountry.atlassian.net/browse/SDK-240)
------------
Target Release
--------------
> SDK-240 Bump version

- package-lock.json
- package.json
- [SDK-238](https://incountry.atlassian.net/browse/SDK-238)
------------
Target Release
--------------
> SDK-238 Support installation from git branch

- README.md
- src/in-crypt.ts
- src/validation/custom-encryption-configs-deep.ts
- src/validation/secrets-data.ts
- tests/unit/in-crypt-tests.ts
- tests/unit/secret-key-accessor-tests.ts
- tests/unit/storage-tests.ts
- tests/unit/validation/secrets-data-test.ts
- [SDK-244](https://incountry.atlassian.net/browse/SDK-244)
------------
Target Release
--------------
> SDK-244 [Node.js SDK] SDK should accept base64 encoded keys in SecretsData instead of utf-8 encoded

- README.md
- package-lock.json
- package.json
- src/in-crypt.ts
- src/validation/custom-encryption-configs-deep.ts
- src/validation/secrets-data.ts
- tests/integration/find-records-tests.ts
- tests/unit/in-crypt-tests.ts
- tests/unit/secret-key-accessor-tests.ts
- tests/unit/storage-tests.ts
- tests/unit/validation/secrets-data-test.ts
- [SDK-249](https://incountry.atlassian.net/browse/SDK-249)
------------
Target Release
--------------
> SDK-249 [Node.js SDK] Release v3.2.0

- package-lock.json
- package.json
- travis-build.sh
- [SDK-263](https://incountry.atlassian.net/browse/SDK-263)
------------
Target Release
--------------
> SDK-263 [Node.js SDK] Merge master into develop

- README.md
- package-lock.json
- package.json
- [SDK-266](https://incountry.atlassian.net/browse/SDK-266)
------------
Target Release
--------------
> SDK-266 [Node.js SDK] File storage README

- README.md
- [SDK-270](https://incountry.atlassian.net/browse/SDK-270)
------------
Target Release
--------------
> SDK-270 [Node.js SDK] Update README introduction section

- README.md
- [SDK-270](https://incountry.atlassian.net/browse/SDK-270)
------------
Target Release
--------------
> SDK-270 [Node.js SDK] Update README introduction section - more readme updates

- README.md
- [SDK-270](https://incountry.atlassian.net/browse/SDK-270)
------------
Target Release
--------------
> SDK-270 [Node.js SDK] Update README introduction section - attachments note

- .travis.yml
- travis-build.sh
- [DEVOPS-2468](https://incountry.atlassian.net/browse/DEVOPS-2468)
------------
These code changes will allow us to use Sonar more flexibly. Now you can select the required version of Sonar in the Travis UI without changing the code.
> DEVOPS-2468: Changing the conditions for downloading Sonar

- README.md
- [SDK-299](https://incountry.atlassian.net/browse/SDK-299)
------------
Target Release
--------------
> SDK-299 Remove apiKey from custom encryption in README, fix mistake.

- README.md
- [SDK-301](https://incountry.atlassian.net/browse/SDK-301)
------------
Target Release
--------------
> SDK-301 [Node.js SDK] Update Readme with new errors description

- README.md
- tests/unit/storage/find-one-tests.ts
- tests/unit/storage/find-tests.ts
- [SDK-279](https://incountry.atlassian.net/browse/SDK-279)
------------
Target Release
--------------
> SDK-279 [Node.js SDK] Fix mistake in comments

- README.md
- examples/.eslintrc
- examples/aws-kms.js
- [SDK-252](https://incountry.atlassian.net/browse/SDK-252)
------------
Target Release
--------------
> SDK-252 [Node.js SDK] AWS KMS Key integration example

- README.md
- [SDK-315](https://incountry.atlassian.net/browse/SDK-315)
------------
Target Release
--------------
> SDK-315 [Node.js SDK] Add information that sorting options will be working only in combination with the non-hashing Storage mode

- README.md
- src/auth-client.ts
- src/storage.ts
- src/validation/storage-options.ts
- tests/integration/common.ts
- tests/unit/api-client-test.ts
- tests/unit/storage/constructor-tests.ts
- tests/unit/validation/storage-options-test.ts
- [SDK-302](https://incountry.atlassian.net/browse/SDK-302)
------------
Target Release
--------------
> SDK-302 [Node.js SDK] Allow oAuth2 token Storage initialization

- package-lock.json
- package.json
- [SDK-319](https://incountry.atlassian.net/browse/SDK-319)
------------
Target Release
--------------
> SDK-319 [Node.js SDK] Release SDK v3.4.0 - bump version

- package-lock.json
- package.json
- src/api-client.ts
- [SDK-320](https://incountry.atlassian.net/browse/SDK-320)
------------
Target Release
--------------
> SDK-320 [Node.js SDK] User cannot attache file with size more than 10Mb

- package-lock.json
- package.json
- src/api-client.ts
- [SDK-321](https://incountry.atlassian.net/browse/SDK-321)
------------
Target Release
--------------
> SDK-321 [Node.js SDK] Release SDK v3.4.1

- README.md
- package-lock.json
- package.json
- src/api-client.ts
- tests/unit/storage/add-attachment-tests.ts
- [SDK-323](https://incountry.atlassian.net/browse/SDK-323)
------------
Target Release
--------------
> SDK-323 [Node.js SDK] Add SDK-specific error when reaching file size limit

- tests/integration/oauth-tests.ts
- [SDK-302](https://incountry.atlassian.net/browse/SDK-302)
------------
Target Release
--------------
> SDK-302 [Node.js SDK] Allow oAuth2 token Storage initialization - 2

- README.md
- src/validation/user-input/find-options.ts
- [SDK-338](https://incountry.atlassian.net/browse/SDK-338)
------------
Target Release
--------------
> SDK-338 [Node.js SDK] Remove service keys from sorting fields in README

- README.md
- src/validation/user-input/find-options.ts
- tests/integration/oauth-tests.ts
- [SDK-339](https://incountry.atlassian.net/browse/SDK-339)
------------
Target Release
--------------
> SDK-339 [Node.js SDK] Merge develop into RC_3.5.0

- README.md
- src/api-client.ts
- src/storage.ts
- tests/integration/healthcheck-tests.ts
- tests/test-helpers/popapi-nock.ts
- tests/unit/api-client-test.ts
- tests/unit/storage/healthcheck-tests.ts
- [SDK-328](https://incountry.atlassian.net/browse/SDK-328)
------------
Target Release
--------------
> SDK-328 [Node.js SDK] add healthcheck method
